language: ruby
rvm:
  - 2.2.0
bundler_args: --without development:staging:production
before_script:
  - cp config/database.travis.yml config/database.yml
  - rake db:create
  - rake db:schema:load
after_script:
  - bundle exec codeclimate-test-reporter
notifications:
  email: false
addons:
  code_climate:
    repo_token: 4d82c5b90b7dc64d6e713f44511dbb02efa930f3095f43ed38ccb71e5db991dc
